# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-07-27 10:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mname', models.CharField(max_length=32)),
                ('down_time', models.DateTimeField(default=datetime.datetime(2019, 7, 27, 18, 3, 46, 733904), verbose_name='下载日期')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('path', models.CharField(max_length=300)),
                ('up_time', models.DateTimeField(default=datetime.datetime(2019, 7, 27, 18, 3, 46, 734904), verbose_name='上传日期')),
                ('is_free', models.IntegerField(choices=[(0, '收费'), (1, '免费')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('content', models.CharField(max_length=164)),
                ('pub_time', models.DateTimeField(default=datetime.datetime(2019, 7, 27, 18, 3, 46, 733904), verbose_name='发布日期')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
                ('vip', models.BooleanField(default=False)),
                ('balance', models.FloatField(default=0)),
                ('utype', models.IntegerField(choices=[(0, '普通用户'), (1, '管理员')], default=0)),
                ('islock', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='notice',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.User'),
        ),
        migrations.AddField(
            model_name='movie',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.User'),
        ),
        migrations.AddField(
            model_name='history',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.User'),
        ),
    ]
